{
    'name': 'Club Management',
    'version': '17.0.1.3.0',
    'category': 'Services',
    'summary': 'Memberships, courts and bookings for The Champions Club',
    'author': 'Hackathon Team',
    'license': 'LGPL-3',
    'depends': ['base', 'web', 'mail', 'account', 'product', 'crm', 'sale_crm', 'point_of_sale', 'stock'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/categories.xml',
        'data/pricelist.xml',
        'data/plans.xml',
        'data/product.xml',
        'data/crm_data.xml',
        'data/crm_pipeline.xml',
        'data/mail_template.xml',
        'data/cron.xml',
        'data/demo_club_data.xml',
        'views/client_actions.xml',
        'views/membership_plan_views.xml',
        'views/partner_views.xml',
        'views/court_views.xml',
        'views/booking_views.xml',
        'wizard/booking_reschedule_views.xml',
        'views/menus.xml',
        'views/report_views.xml',
        'views/order_views.xml',
        'views/crm_lead_views.xml',
    ],
    'demo': [
        'demo/demo_courts.xml',
        'demo/demo_members.xml',
        'demo/demo_products.xml',
        'demo/demo_activity.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'club_management/static/src/scss/champions_variables.scss',
            'club_management/static/src/components/membership_plans/membership_plans.scss',
            'club_management/static/src/components/membership_plans/membership_plans.xml',
            'club_management/static/src/components/membership_plans/membership_plans.js',
            'club_management/static/src/components/court_booking/court_booking.scss',
            'club_management/static/src/components/court_booking/court_booking.xml',
            'club_management/static/src/components/court_booking/court_booking.js',
            'club_management/static/src/components/shop/shop.scss',
            'club_management/static/src/components/shop/shop.xml',
            'club_management/static/src/components/shop/shop.js',
            'club_management/static/src/components/bar_pos/bar_pos.scss',
            'club_management/static/src/components/bar_pos/bar_pos.xml',
            'club_management/static/src/components/bar_pos/bar_pos.js',
            'club_management/static/src/components/owner_dashboard/owner_dashboard.xml',
            'club_management/static/src/components/owner_dashboard/owner_dashboard.js',
        ],
    },
    'application': True,
    'installable': True,
}
