from . import test_member
from . import test_booking_rules
from . import test_pricing
from . import test_availability
from . import test_enquiry
from . import test_pricelists
from . import test_reports
from . import test_cron
from . import test_demo
from . import test_frontend_api
from . import test_crm_flow
from . import test_currency
from . import test_public_booking
from . import test_public_order
from . import test_member_login
from . import test_dashboard
from . import test_owner_reports
from . import test_support
